#!/bin/bash

# NOTE: This file is a TEMPLATE
# The actual version is auto-generated by setup-client.sh with correct paths
# This file is kept for reference only

# Wrapper for check-mentions-notify.py that uses monitoring project's venv
# This provides access to httpx for reporting to the monitoring server

PROJECT_DIR="<auto-generated-by-setup>"

# Check if virtual environment exists
if [ ! -d "$PROJECT_DIR/venv" ]; then
    echo "ERROR: Virtual environment not found at $PROJECT_DIR/venv"
    echo "Run $PROJECT_DIR/setup.sh first"
    exit 1
fi

# Activate virtual environment
source "$PROJECT_DIR/venv/bin/activate"

# Set monitoring server URL
export MONITOR_SERVER_URL="http://localhost:8000"
export CLIENT_ID="$(hostname)"

# Run the Python script
python3 "$HOME/scripts/slack-assistant/check-mentions-notify.py"

# Deactivate when done
deactivate
